### ISSUE TITLE
US_12.001 | Footer > Jenkins version

### ISSUE THREAD

**Issue by NatalieDi** [RedRoverSchool/JenkinsQA_2024_fall#515]
**Description:**
As a user, I want to see the Jenkins version displayed in the footer of the dashboard so that I can quickly verify the version I am using for compatibility and support purposes.

**Acceptance Criteria**

- The footer of the Jenkins dashboard should display the current version number of Jenkins. 
- The version format should follow the standard versioning scheme (e.g. Major.Minor.Patch, e.g. 2.462.3).

**Comment by NatashaShimkiv** [comment]
You can remove from description information about location of Jenkins version.
For example 
As a user, I want to see the Jenkins version  so that I can quickly verify the version I am using for compatibility and support purposes.

And Acceptance Criteria will be like this:
The user should see the current Jenkins version number in the footer of the Jenkins dashboard.

The second point is more technical, not user-related.

Maybe you can add what user see in the Dropdown menu, click on Jenkins version.

**Comment by NatalieDi** [comment]
check please
