### ISSUE TITLE
US_02.001 | Pipeline > View pipeline page

### ISSUE THREAD

**Issue by IrinaNap** [RedRoverSchool/JenkinsQA_2024_fall#553]
**Description:**
As a registered user, I want to view the pipeline page to see the current status of my pipeline, access recent build information, and view build history so that I can monitor the pipeline’s progress and troubleshoot any issues.

**Acceptance Criteria:**

1. The user can navigate to the specific pipeline page from the Jenkins dashboard and view the pipeline details.
2. The user can access actions like "Changes," "Build Now," "Configure," "Delete Pipeline," "Stages," "Rename," and "Pipeline Syntax" in the sidebar.
3. The user can add a description to the pipeline by clicking the "Add description" button on the right.

**Comment by NatashaShimkiv** [comment]
The pipeline page shows the current status of the pipeline (e.g., successful, failed) at the top, with a prominent status icon.
The "Permalinks" section provides quick links to the last build, last stable build, last successful build, and last completed build, each showing the build number and time since execution.
A "Build History" section is visible on the left, listing previous builds with status indicators (e.g., green for success).
Each build entry in the history shows the build number, date, and time, and allows filtering.

This point are more technical then users. I think you can reduce them, leaving what can be voiced from the user's position.
