### ISSUE TITLE
US_02.002 | Pipeline > View changes

### ISSUE THREAD

**Issue by IrinaNap** [RedRoverSchool/JenkinsQA_2024_fall#554]
**Description:**
As a registered user, I want to view recent changes made to the pipeline to see what modifications have been applied in recent builds so that i can track their impact on the build process.

**Acceptance Criteria:**

1. The user can go to the "Changes" section on the pipeline page to view recent code changes and the author of the changes (if available).
2. The user can see the history of changes for each build, identifying which changes were associated with specific builds in the "Build History." 
3. If there are no changes in the builds or multiple SCMs (Source Code Management systems) are in use, the user see message is displayed: "No changes in any of the builds, or multiple SCMs in use."

**Comment by NatashaShimkiv** [comment]
In description should be phrase "so that i"
It may be look like this

As a registered user, I want to view recent changes made to the pipeline so that i can  track their impact on the build process.

The first and second points may be join, i think.
The user can go to the "Changes" section on the pipeline page to view recent code changes and the author of the changes (if available).
You can correct the third point
If there are no changes in the builds or multiple SCMs (Source Code Management systems) are in use, **the user see** message is displayed: "No changes in any of the builds, or multiple SCMs in use."
And you can swap third and fourth points .

I would remove the fifth point.
