### ISSUE TITLE
US_02.003 | Pipeline > Build now

### ISSUE THREAD

**Issue by IrinaNap** [RedRoverSchool/JenkinsQA_2024_fall#555]
**Description:**
As a registered user, I want the ability to start a new build of the project with the current settings so that I can test changes or rerun the build to check for stability.

**Acceptance Criteria:**

1. The user can click the "Build Now" button in the menu on the pipeline page to start a new build of the project.
2. The user can see a new build is added to the "Build History" with the start time and the build status (e.g., in-progress, successful, failed).
3. The user can see the real-time status of the build through an updating indicator next to the build number.
4. After the build completes the user can see an appropriate icon appears (a green checkmark for a successful build, a red cross for a failed one).
5. The user can view the build log and additional details by selecting the corresponding entry in the "Build History."

**Comment by NatashaShimkiv** [comment]
In description should be phrase "so that i"
Please correct it.

I think you can correct the second point 
like this for example

The user can see a new build is added to the "Build History" with the start time and the build status (e.g., in-progress, successful, failed).

and fourth point

After the build completes the user can see an appropriate icon appears (a green checkmark for a successful build, a red cross for a failed one).
