### ISSUE TITLE
US_02.004 | Pipeline > Pipeline Configuration

### ISSUE THREAD

**Issue by IrinaNap** [RedRoverSchool/JenkinsQA_2024_fall#556]
**Description:**
As a registered user, I want to access and modify the configuration of an existing pipeline project to define build stages, set triggers, and manage post-build actions so that I can customize the pipeline's behavior to meet the specific needs of my project.

**Acceptance Criteria:**

1. The user can select the "Configure" option from the pipeline menu to access the configuration settings of the project.
2. The user can define or modify various stages of the pipeline, specifying actions to be executed at each stage.
3. The user can set build triggers, such as automatically starting a build when changes are detected in the source repository.
4. The user can configure post-build actions, such as sending notifications or triggering downstream jobs, to occur upon successful or failed builds.
5. After configuring the settings, the user can save the configuration.
6. Upon saving, user can applied new settings to future builds.

**Comment by NatashaShimkiv** [comment]
In description should be phrase "so that i"
Correct, please.
Like this, for example

As a registered user, I want to access and modify the configuration of an existing pipeline project so that i can to customize the pipeline's behavior to meet the specific needs of my project.

I think you can correct the sixth point 

Upon saving, user can  applied new settings to future builds.
